version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "pizzamia"
      POSTGRES_USER: "pizzamia"
      POSTGRES_PASSWORD: "pizzamia"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "6432:6432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U habrpguser -d habrdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
      restart: unless-stopped
      deploy:
        resources:
          limits:
            cpus: '1'
            memory: 4G